# \bibliography{~/research/todo/bibtest}
* Osteosarcoma 
** Low grade cite:Righi2015                            :lowgradeogs:rizzoli:
of 20 low grade ogs with <50% high grade areas, 11 got chemo and 9 did
not, bth did equally good. Fibroblastic hight grade (vis a vis
osteblastic in conventional ogs) were more common. And mean age was
also higher. Final recommendation was no chemo if high grade area <50
% according to Broder's grading.

* Pallaitive care papers	       :palliative:incurable:cancer:survival:
** Delivering bad news						    :badnews:
SPIKES Setting Perception Invitation Knowledge Empathy Strategy and
summary[[ http://www.medscape.com/viewarticle/856955_2?nlid=98266_944][link]
** Terminal care		  :terminalcare:survival:estimate:palliative:
goals of care,if disase incurable survival estimate and magnitude of
treatment benefit.early and prompt referral to palliative care.
** Why patients leave
The patients described an ideal physician as someone who is confident, empathetic, humane, personal, forthright, respectful, and thorough.
** 
