* Pelvic Exenteration
done in 1 stage. Has a Pelvic part, supralevator part and infralevator
part.
Ureters are cut as low as possible. Rectum is stapled now or after the
infralevator dissection is completed.Low rectal anastomosis had upto
50 % risk of fistula or leak , hence end colostomy is preferred.

Then a continent or incontinent urinary diversion is
performed. Continent uses right colon as a low pressure reservoir with
the ileocecal valve and the appendix as the valve. Incontinent ones
use a segment of the ileum as the reservoir.and a stoma.

The advantage of the continent one is one less stoma.
* 2 stage spino pelvic resections. Abdomino pelvic 
or Localio's technique with a single stage lateral position for a
posterior approach and an anterior transperitoneal approach.

The principles of stabilisation are PPRF(posterioe pelvic ring
fixation) with transiliac bars, SPF (spino pelvic with pedicular
screws) and anterior spinal column fixation (ASCF) using cages or bone
graft.
In one study adding ASCF reduced implant failure rate, but not all
confounding factors could be analysed.

Gutenbergs study showed that indications of SPF are total sacrectomy
and more than 50% resection of both SI joints.
