* Tendon repair
learnt a single modified kessler bite, stitch both ends. Turn the
tendon with the inserted hypodermic needles. Begin the modified
silverskiold stitch from behind, go all around adn stitch it back to
the loose end where you started.
* Henry's approach to volar forearm :
1. Incision medial to the mobile wad toward the radial tuberosity
2. incise fascia and identify interval bewtween BR and FCR
3. Retract BR laterally to identify the sup radial nerve underneath
4. ligate recurrent branches from the radial artery to the BR
5. identify the bicep tendon proximally and retract medially
   protecting the radial artery to expose radial head and neck
6. Distally seperate BR from Pronator teres, retract PT laterally to
   identify supinator beneath, and identify the arcade of Frohse and
   see PIN entering it.
7. Supination moves PIN out of the op field
8. Incise supinator proximal to distal
9. Pronate forearm and incise PT from distal to proximal
10. Supinate to identify PQ, risk of injury to Radial artery, peel PQ
    toward ulna
* Hemi Arthroplasty
 Skin, fat, tensor fascia, glut medius, minimus,capsule.
45 deg neck cut, extract head. Box cut with pirifirmis fossa as
centre, canal finder, rasps.Finish trial. Cement plug,lavage,canal
dry,cement and close in layers.
